Documentation
hoppinger/rest_normalizations pull request #7
Opened 2018-12-18 12:38 UTC by ashwinimone

Readme for custom normalizations

2018-12-18 14:24 UTC, rolfvandekrol requested changes

2018-12-18 14:24 UTC, rolfvandekrol commented on README.md
> +```sh
This is not `sh` code, but `php`

2018-12-18 14:24 UTC, rolfvandekrol commented on README.md
> +Create a .php file in the module directory with the following content. Replace the `<target_identifier>` with the project-specific entity reference field that needs to be embedded into the API respon
Please translate `locaties` to `locations`, and add explanation which target identifiers are accepted and how they should be constructed.

2018-12-18 14:24 UTC, rolfvandekrol commented on README.md
> +```sh
Could you make clear where these code should be placed and how the name of the class relates to the name of the module it is placed in.

2018-12-31 12:55 UTC, ashwinimone commented on README.md
> +Create a .php file in the module directory with the following content. Replace the `<target_identifier>` with the project-specific entity reference field that needs to be embedded into the API respon
Could you explain the "how they should be constructed"?

2019-01-02 08:27 UTC, rolfvandekrol commented on README.md
> +Create a .php file in the module directory with the following content. Replace the `<target_identifier>` with the project-specific entity reference field that needs to be embedded into the API respon
There are three types of valid target identifiers:

* the entity id of the referenced entity type
* `A-B` where `A` is the entity id of the entity type the field is on, and `B` is the name of the field
* `A-B-C` where `A` is the entity id of the entity type the field ion, `B` is the bundle where the field is on, and `C` is the name of the field.

This should be reworded and made a little more clear, but that's the gist. The logic where the valid target identifiers are constructed is here: https://github.com/hoppinger/rest_normalizations/blob/master/src/ComponentGenerator/EntityReferenceTargetFieldGenerator.php#L36-L42

2019-05-08 12:56 UTC, merged